name: GitHub Context

on: 
 workflow_dispatch
jobs:
 github_context:
  runs-on: ubuntu latest
  steps:
   - name: Print Info about Gitgub
     run: |
      echo 'Repository details ${{github.repository}}'
      echo 'Repository id ${{github.repository_id}}'
      echo 'Repository url ${{github.repositoryUrl}}'
      echo 'Worklow name ${{github.workflow}}'
      echo 'Actor ${{github.actor}}'
      echo 'ref details ${{github.ref}}'
      echo 'trigger event ${{github.event_name}}'
      echo 'Run id ${{github.run_id}}'
      echo 'Runner number is ${{github.run_number}}'
