name: Variable

on:
 workflow_dispatch
env:
 MY_VAR: Java
jobs:
  variables:
   env:
     MY_VAR: SringBoot
   runs-on: ubuntu-latest
   steps:
      - name: Print
        run: |
          echo '${{env.MY_VAR}}'
          echo '${{vars.MY_VAR}}'
        env:
         MY_VAR: DevOps
